### ISSUE TITLE
Should the info part be configurable?

### ISSUE THREAD

**Issue by alphafitch** [alphafitch/keijiban#13]
I've been thinking about the info menu, it's job is to display a bit of app info, version number, maybe a "how to use" etc.

Currently we have this as configurable, but I'm not sure if it should be. An end user wouldn't need to change this/shouldn't change this. So maybe we should hard code it into the view?

What do you think @mkherroubi

**Comment by manlikeemkay** [comment]
@alphafitch - I think we should hard code this as people shouldn't change it. Ultimately, there's nothing we can do to stop end users from changing it though.

**Comment by alphafitch** [comment]
Yeah that's a good point. Ok lets make it non-configurable, at least that way it is clear that is shouldn't be edited, even though it technically can be.

I'll convert this to a feature, it's only a small one so I can pick it up now.

**Comment by alphafitch** [comment]
Made the change as discussed so closing this issue
