### ISSUE TITLE
Blurry button icons

### ISSUE THREAD

**Issue by manlikeemkay** [alphafitch/keijiban#16]
In Chrome and Safari web browsers when hovering on the fixed buttons, the icons are blurred.

**Comment by alphafitch** [comment]
Ah man I didn't notice this, I guess the font-awesome icons don't scale well.

Perhaps we should consider a different action on hover? Could invert the colours instead of scaling or something like that

**Comment by manlikeemkay** [comment]
Following a discussion with @alphafitch, it was decided it would be best to remove the scaled button hover state in order to bettter adhere to Material Design guidelines.
